Feature/UI rework
GameMakersToolkit/team-finder pull request #279
Opened 2023-05-28 15:38 UTC by juve-938383

Ooooohhh...is this my first PR? 👀 Let's see if it gets merged.

Changes:
- Advanced Search radio buttons now show default value;
- Added the more contrasting blue for the Possessed Skill labels (because I'm stubborn). I called it real-blue since the other options are actually teal, despite being named blue. Maybe they should be renamed as well?

2023-05-28 18:27 UTC, Willdotwhite commented
@juve-938383 the first and third changes are excellent, thank you :+1: 

Could you drop a screenshot for how the colours look please? If you grab an image and paste it here, Github will automatically upload and embed the image here

2023-05-28 18:40 UTC, juve-938383 commented
It is actually the same colour Sara showed in a version of the site (or  maybe it was the Figma design, not sure which one).
<img width="960" alt="Screenshot_1" src="https://github.com/GameMakersToolkit/team-finder/assets/120019378/c8e12901-205d-4bdc-8686-a05882e18821">

2023-05-28 19:33 UTC, Willdotwhite commented
The hex codes aren't quite right - could you please set them to the following?

```#0090B5 (teal)
#0068E8 (indigo)```

Cheers :D

2023-05-28 19:57 UTC, juve-938383 commented
Done 👍

2023-05-28 21:06 UTC, Willdotwhite approved these changes

2023-05-28 21:08 UTC, Willdotwhite requested changes

2023-05-28 21:08 UTC, Willdotwhite commented on ui/tailwind.config.js
> +        'indigo': '#0068e8'
This line needs a comma at the end, otherwise we can't compile the UI

2023-05-28 21:09 UTC, Willdotwhite commented
Changes look good other than the missing comma (which I only spotted thanks to the GitHub Action - don't review on mobile friends)

2023-05-28 21:34 UTC, juve-938383 commented
*sigh* I am incredibly sorry for dragging such a small thing so long. 😞  I made the colour change straight away in Github and didn't even test it locally.
Anyways, comma added now. Hopefully there is nothing else.

2023-05-29 07:52 UTC, merged

2023-05-29 08:57 UTC, Willdotwhite commented
Don't worry about the timing, asynchronous work is never very quick; I know a guy who had an open PR for ~11 weeks

Thanks again for putting in your first PR!